language: ruby

rvm:
  - 2.5.1

env:
  - RAILS_VERSION=5.2.0
  - RAILS_VERSION=4.2.8

cache:
  directories:
    - /home/travis/.rvm/gems/ruby-2.5.1

addons:
  apt:
    packages:
    - libqtwebkit-dev
    - libqtwebkit4

install: ./ci/build.sh

services:
- xvfb

before_script:
  - export DISPLAY=:99.0
  - sleep 3

script: ./ci/test.sh

jobs:
  include:
    - stage: publish components
      script: 'cd rswag-api'
      deploy:
        gemspec: open_api-rswag-api.gemspec
        gem: open_api-rswag-api
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: publish components
      script: 'cd rswag-specs'
      deploy:
        gemspec: open_api-rswag-specs.gemspec
        gem: open_api-rswag-specs
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: publish components
      script: 'cd rswag-ui'
      deploy:
        gemspec: open_api-rswag-ui.gemspec
        gem: open_api-rswag-ui
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: publish rswag
      script: 'cd rswag'
      deploy:
        gemspec: open_api-rswag.gemspec
        gem: open_api-rswag
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true
